inherit_from:
  - .rubocop_airbnb.yml
inherit_gem:
  rubocop-config-prettier: config/rubocop.yml
# prettier
Style/PercentLiteralDelimiters:
  Enabled: false
Airbnb/OptArgParameters:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
